import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import {ThemePalette} from '@angular/material/core';

export interface ChipColor {
  name: string;
  color: ThemePalette;
}

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrl: './auth.component.css'
})
export class AuthComponent implements OnInit{

  authForm: FormGroup;
  OAuthTooltip="Enables validation of JWT tokens (OAuth) that have been issued by a third party identity provider (e.g.: OpenID Connect)";
  tokenSignTooltip="Helps legacy applications to sign JWT tokens generated by backends that weren't ready for JWT yet.";
  basicAuthTooltip="The Basic Authentication plugin protects the access to selected endpoints using basic username and password credentials via htpasswd.";
  availableColors: ChipColor[] = [
    {name: 'none', color: undefined},
    {name: 'OAuth Format 1', color: 'primary'},
    {name: 'OAuth Format 2', color: 'accent'},
    {name: 'OAuth Format 3', color: 'warn'},
  ];

  constructor(private fb:FormBuilder){
    this.authForm = this.fb.group({
      isOAuthActive:[false],
      isTokenSiginig:[false],
      isBasicAuthActive:[false],
      
    })
  }

  ngOnInit(): void {
    throw new Error('Method not implemented.');
  }

  

}
