import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';


@Component({
  selector: 'app-openapi',
  templateUrl: './openapi.component.html',
  styleUrl: './openapi.component.css'
})
export class OpenapiComponent {
  docTooltip="The OpenAPI or Swagger documentation is automatically generated by the KrakenD Enterprise binary when you use the krakend generate openapi command."
  formGroupOpenapi: FormGroup;

  tagsArray:string[]=[];
  audienceArray:string[]=[];
  
  constructor(private formBuilder: FormBuilder) {
    this.formGroupOpenapi = this.formBuilder.group({
      summary: [''],
      description: [''],
      tags: [''],
      audiences: [''],
      example: [''],
      isDocumentationActive:[false],
      tagsArrayValue:[[]],
      audienceArrayValue:[[]]
    })
  }

  addParameter(fieldName: 'audiences' | 'tags') {
    const fieldValue = this.formGroupOpenapi.get(fieldName)?.value;
console.log(fieldName);

    if (fieldName) {
      if(fieldName === 'audiences'){
        this.audienceArray.push(fieldValue);
        this.formGroupOpenapi.get('audienceArrayValue')?.setValue([...this.audienceArray]);
      
    }else if(fieldName === 'tags'){
      this.tagsArray.push(fieldValue);
      console.log(this.tagsArray);
      
      this.formGroupOpenapi.get('tagsArrayValue')?.setValue([...this.tagsArray]);
    }
    this.formGroupOpenapi.get(fieldName)?.reset();
  }
}
  removeParameter(index: number, fieldName:'audiences' | 'tags') {
    if(fieldName === "audiences"){
      this.audienceArray.splice(index,1);
      this.formGroupOpenapi.get('audienceArrayValue')?.setValue([...this.audienceArray]);
    }else if(fieldName === 'tags'){
      this.tagsArray.splice(index,1);
      this.formGroupOpenapi.get('tagsArrayValue')?.setValue([...this.tagsArray]);
    }
  }
}   
